### ISSUE TITLE
Problems with Arduino Code

### ISSUE THREAD

**Issue by BeccaCampbell** [spenceraxani/CosmicWatch-Desktop-Muon-Detector#9]
So I have downloaded the arduino coding program and followed the directions to install the specific libraries, but the code provided has "const byte LED" defined and then redefined in the next line, which the program doesn't like when compiling the code. I have tried several different ways of getting rid of this problem, but my arduino still doesn't seem to be communicating with the rest of the device (LED wont turn on, OLED wont turn on, and no counts are being received). I doubt this is my only problem, but it's the only one I can figure out.

Any insight would be greatly appreciated. Thanks!

**Comment by mbanders** [comment]
Created a pull request to fix the error: https://github.com/spenceraxani/CosmicWatch-Desktop-Muon-Detector/pull/10

**Comment by spenceraxani** [comment]
Hi,

It sounds like the constant variable was defined twice. I see that Mike Anderson removed the line, so it should work now. 

Thanks,

Spencer

**Comment by BeccaCampbell** [comment]
Thank you.

I uploaded the corrected code but I still cant get anything to work, so I think I have larger problems at play, But I have no idea what it is at this point.

Thanks for your help.
Becca
